import imagePaths from "../../../Images/chambers_small/Coop_Small_Images";

const courses = {
  course_1: [
    {
      id: 47741,
      title: "Doors",
      chapter_name: "Team Building",
      image: imagePaths[47741],
    },
    {
      id: 47825,
      title: "Buttons",
      chapter_name: "Team Building",
      image: imagePaths[47825],
    },
    {
      id: 47828,
      title: "Lasers",
      chapter_name: "Team Building",
      image: imagePaths[47828],
    },
    {
      id: 47829,
      title: "Rat Maze",
      chapter_name: "Team Building",
      image: imagePaths[47829],
    },
    {
      id: 45467,
      title: "Laser Crusher",
      chapter_name: "Team Building",
      image: imagePaths[45467],
    },
    {
      id: 46362,
      title: "Behind the Scenes",
      chapter_name: "Team Building",
      image: imagePaths[46362],
    },
  ],
  course_2: [
    {
      id: 47831,
      title: "Flings",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47831],
    },
    {
      id: 47833,
      title: "Infinifling",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47833],
    },
    {
      id: 47835,
      title: "Team Retrieval",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47835],
    },
    {
      id: 47837,
      title: "Vertical Flings",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47837],
    },
    {
      id: 47840,
      title: "Catapults",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47840],
    },
    {
      id: 47841,
      title: "Multifling",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47841],
    },
    {
      id: 47844,
      title: "Fling Crusers",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47844],
    },
    {
      id: 47845,
      title: "Industrial Fan",
      chapter_name: "Mass and Velocity",
      image: imagePaths[47845],
    },
  ],
  course_3: [
    {
      id: 47848,
      title: "Cooperative Bridges",
      chapter_name: "Hard Light",
      image: imagePaths[47848],
    },
    {
      id: 47849,
      title: "Bridge Swap",
      chapter_name: "Hard Light",
      image: imagePaths[47849],
    },
    {
      id: 47854,
      title: "Fling Block",
      chapter_name: "Hard Light",
      image: imagePaths[47854],
    },
    {
      id: 47856,
      title: "Catapult Block",
      chapter_name: "Hard Light",
      image: imagePaths[47856],
    },
    {
      id: 47858,
      title: "Bridge Fling",
      chapter_name: "Hard Light",
      image: imagePaths[47858],
    },
    {
      id: 47861,
      title: "Turret Walls",
      chapter_name: "Hard Light",
      image: imagePaths[47861],
    },
    {
      id: 52642,
      title: "Turret Assassin",
      chapter_name: "Hard Light",
      image: imagePaths[52642],
    },
    {
      id: 52660,
      title: "Bridge Testing",
      chapter_name: "Hard Light",
      image: imagePaths[52660],
    },
  ],
  course_4: [
    {
      id: 52662,
      title: "Cooperative Funnels",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52662],
    },
    {
      id: 52663,
      title: "Funnel Drill",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52663],
    },
    {
      id: 52665,
      title: "Funnel Catch",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52665],
    },
    {
      id: 52667,
      title: "Funnel Laser",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52667],
    },
    {
      id: 52671,
      title: "Cooperative Polarity",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52671],
    },
    {
      id: 52687,
      title: "Funnel Hop",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52687],
    },
    {
      id: 52689,
      title: "Advanced Polarity",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52689],
    },
    {
      id: 52691,
      title: "Funnel Maze",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52691],
    },
    {
      id: 52777,
      title: "Turret Warehouse",
      chapter_name: "Excursion Funnels",
      image: imagePaths[52777],
    },
  ],
  course_5: [
    {
      id: 52694,
      title: "Repulsion Jumps",
      chapter_name: "Mobility Gels",
      image: imagePaths[52694],
    },
    {
      id: 52711,
      title: "Double Bounce",
      chapter_name: "Mobility Gels",
      image: imagePaths[52711],
    },
    {
      id: 52714,
      title: "Bridge Repulsion",
      chapter_name: "Mobility Gels",
      image: imagePaths[52714],
    },
    {
      id: 52715,
      title: "Wall Repulsion",
      chapter_name: "Mobility Gels",
      image: imagePaths[52715],
    },
    {
      id: 52717,
      title: "Propulsion Crushers",
      chapter_name: "Mobility Gels",
      image: imagePaths[52717],
    },
    {
      id: 52735,
      title: "Turret Ninja",
      chapter_name: "Mobility Gels",
      image: imagePaths[52735],
    },
    {
      id: 52738,
      title: "Propulsion Retrieval",
      chapter_name: "Mobility Gels",
      image: imagePaths[52738],
    },
    {
      id: 52740,
      title: "Vault Entrance",
      chapter_name: "Mobility Gels",
      image: imagePaths[52740],
    },
  ],
  course_6: [
    {
      id: 49341,
      title: "Separation",
      chapter_name: "Art Therapy",
      image: imagePaths[49341],
    },
    {
      id: 49343,
      title: "Triple Axis",
      chapter_name: "Art Therapy",
      image: imagePaths[49343],
    },
    {
      id: 49345,
      title: "Catapult Catch",
      chapter_name: "Art Therapy",
      image: imagePaths[49345],
    },
    {
      id: 49347,
      title: "Bridge Gels",
      chapter_name: "Art Therapy",
      image: imagePaths[49347],
    },
    {
      id: 49349,
      title: "Maintenance",
      chapter_name: "Art Therapy",
      image: imagePaths[49349],
    },
    {
      id: 49351,
      title: "Bridge Catch",
      chapter_name: "Art Therapy",
      image: imagePaths[49351],
    },
    {
      id: 52757,
      title: "Double Lift",
      chapter_name: "Art Therapy",
      image: imagePaths[52757],
    },
    {
      id: 52759,
      title: "Gel Maze",
      chapter_name: "Art Therapy",
      image: imagePaths[52759],
    },
    {
      id: 48287,
      title: "Crazier Box",
      chapter_name: "Art Therapy",
      image: imagePaths[48287],
    },
  ],
};

export default courses;
